/**
 \file          can_aux_vlv.h
 \author        Alexey Evlampjev
 \date          January, 2018
 \brief         Auxiliary defines and functions for Wartsila project CAN bus
 \note          Only universal for all nodes defines and functions are placing 
                at this file
 */

#ifndef __can_aux_vlv_H_
#define __can_aux_vlv_H_

#ifdef __cplusplus
 extern "C" {
#endif

#include "can_aux_global.h"

#pragma anon_unions


// must be power of 2
#define CANVLV_QUEUE_SIZE 16
     
	
typedef enum
{	
    // 1
    KSIVLV_ICM_BASE = 0x0001,
    KSIVLV_ICM_NOTICE      = KSIVLV_ICM_BASE + KSI_NOTICE_BASE,
    KSIVLV_ICM_GENERAL     = KSIVLV_ICM_BASE + KSI_GENERAL_BASE,
    KSIVLV_ICM_SERVICE     = KSIVLV_ICM_BASE + KSI_SERVICE_BASE,
    // 2
    //KSI_VCMA_BASE = 0x0004,
    //KSI_VCMA_NOTICE     = KSI_VCMA_BASE + KSI_NOTICE_BASE,
    //KSI_VCMA_GENERAL    = KSI_VCMA_BASE + KSI_GENERAL_BASE,
    //KSI_VCMA_SERVICE    = KSI_VCMA_BASE + KSI_SERVICE_BASE,
    // 3
    //KSI_VCMB_BASE = 0x0005,
    //KSI_VCMB_NOTICE     = KSI_VCMB_BASE + KSI_NOTICE_BASE,
    //KSI_VCMB_GENERAL    = KSI_VCMB_BASE + KSI_GENERAL_BASE,
    //KSI_VCMB_SERVICE    = KSI_VCMB_BASE + KSI_SERVICE_BASE,
    // 4
    KSIVLV_KSIA1_BASE = 0x000F,
    KSIVLV_KSIA1_NOTICE    = KSIVLV_KSIA1_BASE + KSI_NOTICE_BASE,
    KSIVLV_KSIA1_GENERAL   = KSIVLV_KSIA1_BASE + KSI_GENERAL_BASE,
    KSIVLV_KSIA1_SERVICE   = KSIVLV_KSIA1_BASE + KSI_SERVICE_BASE,
    // 5
    KSIVLV_KSIA2_BASE = 0x0010,
    KSIVLV_KSIA2_NOTICE    = KSIVLV_KSIA2_BASE + KSI_NOTICE_BASE,
    KSIVLV_KSIA2_GENERAL   = KSIVLV_KSIA2_BASE + KSI_GENERAL_BASE,
    KSIVLV_KSIA2_SERVICE   = KSIVLV_KSIA2_BASE + KSI_SERVICE_BASE,
    // 6
    KSIVLV_KSIA3_BASE = 0x0011,
    KSIVLV_KSIA3_NOTICE    = KSIVLV_KSIA3_BASE + KSI_NOTICE_BASE,
    KSIVLV_KSIA3_GENERAL   = KSIVLV_KSIA3_BASE + KSI_GENERAL_BASE,
    KSIVLV_KSIA3_SERVICE   = KSIVLV_KSIA3_BASE + KSI_SERVICE_BASE,
    // 7
    KSIVLV_KSIA4_BASE = 0x0012,
    KSIVLV_KSIA4_NOTICE    = KSIVLV_KSIA4_BASE + KSI_NOTICE_BASE,
    KSIVLV_KSIA4_GENERAL   = KSIVLV_KSIA4_BASE + KSI_GENERAL_BASE,
    KSIVLV_KSIA4_SERVICE   = KSIVLV_KSIA4_BASE + KSI_SERVICE_BASE,
    // 8
    KSIVLV_KSIA5_BASE = 0x0013,
    KSIVLV_KSIA5_NOTICE    = KSIVLV_KSIA5_BASE + KSI_NOTICE_BASE,
    KSIVLV_KSIA5_GENERAL   = KSIVLV_KSIA5_BASE + KSI_GENERAL_BASE,
    KSIVLV_KSIA5_SERVICE   = KSIVLV_KSIA5_BASE + KSI_SERVICE_BASE,
    // 9
    KSIVLV_KSIA6_BASE = 0x0014,
    KSIVLV_KSIA6_GENERAL   = KSIVLV_KSIA6_BASE + KSI_GENERAL_BASE,
    KSIVLV_KSIA6_SERVICE   = KSIVLV_KSIA6_BASE + KSI_SERVICE_BASE,
    KSIVLV_KSIA6_NOTICE    = KSIVLV_KSIA6_BASE + KSI_NOTICE_BASE,
    // 10
    KSIVLV_KSIA7_BASE = 0x0015,
    KSIVLV_KSIA7_GENERAL   = KSIVLV_KSIA7_BASE + KSI_GENERAL_BASE,
    KSIVLV_KSIA7_SERVICE   = KSIVLV_KSIA7_BASE + KSI_SERVICE_BASE,
    KSIVLV_KSIA7_NOTICE    = KSIVLV_KSIA7_BASE + KSI_NOTICE_BASE,
    // 11
    KSIVLV_KSIA8_BASE = 0x0016,
    KSIVLV_KSIA8_GENERAL   = KSIVLV_KSIA8_BASE + KSI_GENERAL_BASE,
    KSIVLV_KSIA8_SERVICE   = KSIVLV_KSIA8_BASE + KSI_SERVICE_BASE,
    KSIVLV_KSIA8_NOTICE    = KSIVLV_KSIA8_BASE + KSI_NOTICE_BASE,
    // 12
    KSIVLV_KSIA9_BASE = 0x0017,
    KSIVLV_KSIA9_GENERAL   = KSIVLV_KSIA9_BASE + KSI_GENERAL_BASE,
    KSIVLV_KSIA9_SERVICE   = KSIVLV_KSIA9_BASE + KSI_SERVICE_BASE,
    KSIVLV_KSIA9_NOTICE    = KSIVLV_KSIA9_BASE + KSI_NOTICE_BASE,
    // 12
    KSIVLV_KSIA10_BASE = 0x0018,
    KSIVLV_KSIA10_GENERAL   = KSIVLV_KSIA10_BASE + KSI_GENERAL_BASE,
    KSIVLV_KSIA10_SERVICE   = KSIVLV_KSIA10_BASE + KSI_SERVICE_BASE,
    KSIVLV_KSIA10_NOTICE    = KSIVLV_KSIA10_BASE + KSI_NOTICE_BASE,
		// 12
    KSIVLV_KSIA11_BASE = 0x0019,
    KSIVLV_KSIA11_GENERAL   = KSIVLV_KSIA11_BASE + KSI_GENERAL_BASE,
    KSIVLV_KSIA11_SERVICE   = KSIVLV_KSIA11_BASE + KSI_SERVICE_BASE,
    KSIVLV_KSIA11_NOTICE    = KSIVLV_KSIA11_BASE + KSI_NOTICE_BASE,
		// 12
    KSIVLV_KSIA12_BASE = 0x001A,
    KSIVLV_KSIA12_GENERAL   = KSIVLV_KSIA12_BASE + KSI_GENERAL_BASE,
    KSIVLV_KSIA12_SERVICE   = KSIVLV_KSIA12_BASE + KSI_SERVICE_BASE,
    KSIVLV_KSIA12_NOTICE    = KSIVLV_KSIA12_BASE + KSI_NOTICE_BASE,
    // 13
    KSIVLV_KSIB1_BASE = 0x001B,
    KSIVLV_KSIB1_NOTICE    = KSIVLV_KSIB1_BASE + KSI_NOTICE_BASE,
    KSIVLV_KSIB1_GENERAL   = KSIVLV_KSIB1_BASE + KSI_GENERAL_BASE,
    KSIVLV_KSIB1_SERVICE   = KSIVLV_KSIB1_BASE + KSI_SERVICE_BASE,
    // 14
    KSIVLV_KSIB2_BASE = 0x001C,
    KSIVLV_KSIB2_NOTICE    = KSIVLV_KSIB2_BASE + KSI_NOTICE_BASE,
    KSIVLV_KSIB2_GENERAL   = KSIVLV_KSIB2_BASE + KSI_GENERAL_BASE,
    KSIVLV_KSIB2_SERVICE   = KSIVLV_KSIB2_BASE + KSI_SERVICE_BASE,
    // 15
    KSIVLV_KSIB3_BASE = 0x001D,
    KSIVLV_KSIB3_NOTICE    = KSIVLV_KSIB3_BASE + KSI_NOTICE_BASE,
    KSIVLV_KSIB3_GENERAL   = KSIVLV_KSIB3_BASE + KSI_GENERAL_BASE,
    KSIVLV_KSIB3_SERVICE   = KSIVLV_KSIB3_BASE + KSI_SERVICE_BASE,
    // 16
    KSIVLV_KSIB4_BASE = 0x001E,
    KSIVLV_KSIB4_NOTICE    = KSIVLV_KSIB4_BASE + KSI_NOTICE_BASE,
    KSIVLV_KSIB4_GENERAL   = KSIVLV_KSIB4_BASE + KSI_GENERAL_BASE,
    KSIVLV_KSIB4_SERVICE   = KSIVLV_KSIB4_BASE + KSI_SERVICE_BASE,
    // 17
    KSIVLV_KSIB5_BASE = 0x001F,
    KSIVLV_KSIB5_NOTICE    = KSIVLV_KSIB5_BASE + KSI_NOTICE_BASE,
    KSIVLV_KSIB5_GENERAL   = KSIVLV_KSIB5_BASE + KSI_GENERAL_BASE,
    KSIVLV_KSIB5_SERVICE   = KSIVLV_KSIB5_BASE + KSI_SERVICE_BASE,
    // 18
    KSIVLV_KSIB6_BASE = 0x0020,
    KSIVLV_KSIB6_GENERAL   = KSIVLV_KSIB6_BASE + KSI_GENERAL_BASE,
    KSIVLV_KSIB6_SERVICE   = KSIVLV_KSIB6_BASE + KSI_SERVICE_BASE,
    KSIVLV_KSIB6_NOTICE    = KSIVLV_KSIB6_BASE + KSI_NOTICE_BASE ,
    // 19
    KSIVLV_KSIB7_BASE = 0x0021,
    KSIVLV_KSIB7_GENERAL   = KSIVLV_KSIB7_BASE + KSI_GENERAL_BASE,
    KSIVLV_KSIB7_SERVICE   = KSIVLV_KSIB7_BASE + KSI_SERVICE_BASE,
    KSIVLV_KSIB7_NOTICE    = KSIVLV_KSIB7_BASE + KSI_NOTICE_BASE,
		 // 19
    KSIVLV_KSIB8_BASE = 0x0022,
    KSIVLV_KSIB8_GENERAL   = KSIVLV_KSIB8_BASE + KSI_GENERAL_BASE,
    KSIVLV_KSIB8_SERVICE   = KSIVLV_KSIB8_BASE + KSI_SERVICE_BASE,
    KSIVLV_KSIB8_NOTICE    = KSIVLV_KSIB8_BASE + KSI_NOTICE_BASE,
		 // 19
    KSIVLV_KSIB9_BASE = 0x0023,
    KSIVLV_KSIB9_GENERAL   = KSIVLV_KSIB9_BASE + KSI_GENERAL_BASE,
    KSIVLV_KSIB9_SERVICE   = KSIVLV_KSIB9_BASE + KSI_SERVICE_BASE,
    KSIVLV_KSIB9_NOTICE    = KSIVLV_KSIB9_BASE + KSI_NOTICE_BASE,
		 // 19
    KSIVLV_KSIB10_BASE = 0x0024,
    KSIVLV_KSIB10_GENERAL   = KSIVLV_KSIB10_BASE + KSI_GENERAL_BASE,
    KSIVLV_KSIB10_SERVICE   = KSIVLV_KSIB10_BASE + KSI_SERVICE_BASE,
    KSIVLV_KSIB10_NOTICE    = KSIVLV_KSIB10_BASE + KSI_NOTICE_BASE,
		 // 19
    KSIVLV_KSIB11_BASE = 0x0025,
    KSIVLV_KSIB11_GENERAL   = KSIVLV_KSIB11_BASE + KSI_GENERAL_BASE,
    KSIVLV_KSIB11_SERVICE   = KSIVLV_KSIB11_BASE + KSI_SERVICE_BASE,
    KSIVLV_KSIB11_NOTICE    = KSIVLV_KSIB11_BASE + KSI_NOTICE_BASE,
		 // 19
    KSIVLV_KSIB12_BASE = 0x0026,
    KSIVLV_KSIB12_GENERAL   = KSIVLV_KSIB12_BASE + KSI_GENERAL_BASE,
    KSIVLV_KSIB12_SERVICE   = KSIVLV_KSIB12_BASE + KSI_SERVICE_BASE,
    KSIVLV_KSIB12_NOTICE    = KSIVLV_KSIB12_BASE + KSI_NOTICE_BASE,
    // 20
    KSI_CFG1_BASE = 0x0041,
    KSI_CFG1_GENERAL   = KSI_CFG1_BASE + KSI_GENERAL_BASE,
    KSI_CFG1_SERVICE   = KSI_CFG1_BASE + KSI_SERVICE_BASE,
    KSI_CFG1_NOTICE    = KSI_CFG1_BASE + KSI_NOTICE_BASE,

    KSI_MAX_STDID = 0x07FF
    // 21
 /*   KSIVLV_KSIB9_BASE = 0x0022
    KSIVLV_KSIB9_GENERAL   = KSIVLV_KSIB9_BASE + KSI_GENERAL_BASE,
    KSIVLV_KSIB9_SERVICE   = KSIVLV_KSIB9_BASE + KSI_SERVICE_BASE,
    KSIVLV_KSIB9_NOTICE    = KSIVLV_KSIB9_BASE + KSI_NOTICE_BASE,
    // 22
    KSIVLV_KSIB10_BASE = 0x0023,
    KSIVLV_KSIB10_GENERAL   = KSIVLV_KSIB10_BASE + KSI_GENERAL_BASE,
    KSIVLV_KSIB10_SERVICE   = KSIVLV_KSIB10_BASE + KSI_SERVICE_BASE,
    KSIVLV_KSIB10_NOTICE    = KSIVLV_KSIB10_BASE + KSI_NOTICE_BASE,
    // 23
    //KSI_CFG2_BASE = 0x0042,
    //KSI_CFG2_GENERAL   = KSI_CFG2_BASE + KSI_GENERAL_BASE,
    //KSI_CFG2_SERVICE   = KSI_CFG2_BASE + KSI_SERVICE_BASE,
    //KSI_CFG2_NOTICE    = KSI_CFG2_BASE + KSI_NOTICE_BASE,
    // 24
    //KSI_CFG3_BASE = 0x0043,
    //KSI_CFG3_GENERAL   = KSI_CFG3_BASE + KSI_GENERAL_BASE,
    //KSI_CFG3_SERVICE   = KSI_CFG3_BASE + KSI_SERVICE_BASE,
    //KSI_CFG3_NOTICE    = KSI_CFG3_BASE + KSI_NOTICE_BASE,*/
//    KSI_MAX_STDID = 20;
} canvlv_stdid_t __attribute__((aligned(4)));



// идентификаторы сообщений (команд)модуля распределения тактирования клапанаов
typedef enum{																															//Data			//	NOTICE/GENERAL/SERVICE	
	CANVLVMSG_MRTK_START									= 0x2,								//------		//	GENERAL	
	CANVLVMSG_MRTK_STOP										= 0x3,								//------		//	NOTICE		
	CANVLVMSG_MRTK_DEBLOCK								= 0x4,								//------		//	GENERAL
	CANVLVMSG_MRTK_PING 									= 0x5,								//------		//	GENERAL
	CANVLVMSG_MRTK_TO_VCU_MODE_REQ				= 0x11,								//------		//	GENERAL
	CANVLVMSG_CFG_ON											= 0x21,								//nn----		//	GENERAL		// nn - номер модуля, переводимого в режим конфигурации
	CANVLVMSG_CFG_WRITEPARAM							= 0x22,								//nndddd		//	SERVICE   // nn - номер параметра, dddd - значение параметра
	CANVLVMSG_CFG_RAEDPARAM								= 0x23,								//nn--NN		//	SERVICE   // nn - номер модуля, NN - номер параметра
	CANVLVMSG_CFG_ACCEPTPARAM							= 0x25,								//------		//	SERVICE   
	CANVLVMSG_CFG_CRCPARAM_REQ						= 0x26,								//nn----		//	SERVICE   // nn - номер модуля,
} canvlvmsg_mrtk_t;
// идентификаторы сообщений (команд)модуля управления клапанами
typedef enum{																															//Data			//	NOTICE/GENERAL/SERVICE	
	CANVLVMSG_VCU_PING 										= 0x5,								//--dddd		//	GENERAL		// dddd - значение температуры мк МУК
	CANVLVMSG_VCU_MODE										= 0x1,								//----nn		//	GENERAL		//  nn - код режима МУК
	CANVLVMSG_VCU_ERROR										= 0x2,								//NN--nn		//	NOTICE		// nn - номер канала, NN - номер ошибки
	CANVLVMSG_CFG_READY										= 0x21,								//------		//	SERVICE
	CANVLVMSG_CFG_PARAMVAL								= 0x22,								//nndddd		//	SERVICE   // nn - номер параметра, dddd - значение параметра 
	CANVLVMSG_CFG_CONFIRM									= 0x23,								//------		//	SERVICE 
	CANVLVMSG_CFG_CRCVAL									= 0x24,								//--dddd		//	SERVICE		//  dddd - значение CRC 
	
//  CANVLVMSG_KSI_PING 										= 0x5,	
//	CANVLVMSG_KSI_OFFSET 									= 0x1,	
//	CANVLVMSG_KSI_SYNC 										= 0x2,	
	
//	CANVLVMSG_KSI_KNOCK 									= 3,	
} canvlvmsg_vcu_t;

	typedef enum{																															//Data			//	NOTICE/GENERAL/SERVICE	
  CANVLVMSG_KSI_PING 										= 0x5,	
	CANVLVMSG_KSI_OFFSET 									= 0x2,	
	CANVLVMSG_KSI_SYNC 										= 0x1,	
	
	CANVLVMSG_KSI_KNOCK 									= 0x3,	
} canvlvmsg_ksi_t;

		 	 

#ifdef __cplusplus
}
#endif
#endif /* __can_aux_vlv_H */
